language: node_js
node_js:
- 6
install: npm install
script:
- npm run build
- npm run storybook:build
deploy:
  - provider: npm
    email: onap.sdc@gmail.com
    api_key: $NPM_TOKEN
    skip_cleanup: true
    on:
      tags: true
      repo: onap-sdc/onap-ui-angular
  - provider: pages
    repo: onap-sdc/onap-ui-angular
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    local_dir: .storybook-out
    on:
      branch: master
